- name: Ensure wireguard package installed
  apt:
    name: wireguard
    state: present

- name: Ensure prometheus-node-exporter package installed
  apt:
    name: prometheus-node-exporter
    state: present

- name: Enable IPv4 forwarding in sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    reload: yes

- name: Create gateway agent binary directory
  file:
    path: /opt/nais-device/bin
    state: directory
    mode: '0755'

- name: Download gateway agent
  get_url:
    dest: /opt/nais-device/bin/gateway-agent
    force: yes
    url: https://github.com/nais/device/releases/download/2020-11-19-11847c0/gateway-agent
    backup: yes
    mode: 0755
  notify:
    - restart_gateway-agent

- name: Create gateway config dir
  file:
    path: /usr/local/etc/nais-device
    state: directory
    mode: '0750'

- name: Generate wireguard public key
  shell: umask 077 && wg genkey > /usr/local/etc/nais-device/private.key
  args:
    creates: /usr/local/etc/nais-device/private.key

- name: Get apiserver password
  shell: gcloud --project nais-device secrets versions access latest --secret {{ gcp_project }}_{{ name }}_api-server-password > /usr/local/etc/nais-device/apiserver_password
  args:
    creates: /usr/local/etc/nais-device/apiserver_password
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

- name: Install gateway agent systemd unit file
  template:
    src: gateway-agent.service.j2
    dest: /etc/systemd/system/gateway-agent.service
  notify:
    - restart_gateway-agent

- name: Ensure gateway-agent is enabled
  systemd:
    name: gateway-agent
    enabled: yes
    daemon_reload: yes

- name: Ensure gateway-agent is started
  systemd:
    name: gateway-agent
    state: started
- include_tasks: install_dmesg_to_json.yml
- include_tasks: set_iptables_rulesv4_outset.yml
