- name: Ensure gpg package installed
  apt:
    name: gpg
    state: present

- name: Ensure prometheus-node-exporter package installed
  apt:
    name: prometheus-node-exporter
    state: present

- name: Set up apt-key for controlplane repo
  apt_key:
    url: https://europe-north1-apt.pkg.dev/doc/repo-signing-key.gpg
    state: present

- name: Set up controlplane repo
  apt_repository:
    repo: 'deb [arch=amd64] https://europe-north1-apt.pkg.dev/projects/naisdevice controlplane main'
    state: present

- name: Ensure gateway-agent package installed
  apt:
    name: gateway-agent
    state: present

- name: Enable IPv4 forwarding in sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    reload: yes

- name: Remove old gateway agent binary directory
  file:
    path: /opt/nais-device
    state: absent

- name: Remove old gateway agent systemd unit file
  file:
    state: absent
    path: /etc/systemd/system/gateway-agent.service

- name: Ensure gateway-agent is enabled
  systemd:
    name: gateway-agent
    enabled: yes
    daemon_reload: yes

- name: Ensure gateway-agent is started
  systemd:
    name: gateway-agent
    state: started
- include_tasks: install_dmesg_to_json.yml
- include_tasks: set_iptables_rulesv4_outset.yml

- name: Add logrotate config
  template:
    owner: root
    group: root
    mode: 640
    src: logrotate-gateway-agent.j2
    dest: /etc/logrotate.d/naisdevice-gateway-agent
